[Settings]
    "siteId": "605d0d3c-8892-4d67-ac04-2936ffdee8ff"
[build]
    functions = "functions"
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
